### ISSUE TITLE
Updated version

### ISSUE THREAD

**Issue by juvinski** [skeetermcbee/letsrobot-mebo#1]
Hi,

have can you help me with a question?
Where I can download the lastest firmware for Mebo and how can I upload that to the Robot ?
I had a Ximpatico Robot - is a custom firmware mebo and this firmware is not good enought, and they didn't provide the orignal firmware form Mebo and I wish to try.

thanks for your help.

**Comment by bwookieeeee** [comment]
This repo is abandoned. You should check out if the parent repo of this fork has any newer updates, or if @remotv has a repo.
